### ISSUE TITLE
Make Forkable

### ISSUE THREAD

**Issue by acatejr** [cloudmesh-community/hid-sample#4]
If you make this repo forkable, I can help with some of the spelling issues that might lead to confusion.

**Comment by laszewsk** [comment]
can you explain to me why it is not forkable, i see 4 forks. I like to learn how i can make it better. Probably there is a feature i do not know about.

**Comment by acatejr** [comment]
I tried forking the project and github would not let me.  Sorry, I should have included some text on what github said.  Let me get that info and will update.

**Comment by acatejr** [comment]
Was able to fork today.
